# Generated by Django 5.1.1 on 2025-03-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal_dev', '0003_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category_con',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post_con',
            new_name='post',
        ),
    ]
